version: "3.8"
services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    ports:
      - 27017:${MONGO_PORT}
    volumes:
      - mongodb_data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:${MONGO_PORT}/${MONGO_DB_NAME}?authSource=admin
      - APP_PORT=${APP_PORT}
      - VERBOSE=${VERBOSE}
      - DEBUG=${DEBUG}
      - TRACE=${TRACE}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
