version: "3.8"
services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    ports:
      - 27017:${MONGO_PORT}
    volumes:
      - mongodb_data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@content-crafters-db.xpn750n.mongodb.net/?retryWrites=true&w=majority&appName=${MONGO_DB_NAME}
      - APP_PORT=${APP_PORT}
      - VERBOSE=${VERBOSE}
      - DEBUG=${DEBUG}
      - TRACE=${TRACE}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:${APP_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:
