services:
  - type: web
    name: content crafters api
    runtime: rust
    repo: https://github.com/jabibamman/content_crafters
    region: frankfurt # optional (defaults to oregon)
    buildCommand: ./build.sh
    startCommand: cargo run --release
    plan: free # optional (defaults to starter instance type)
    branch: master # optional (defaults to master)
    envVars:
      - key: MONGO_URI
        sync: false # provide MONGO_URI in the Render Dashboard

      - key: MONGO_USERNAME
        sync: false # provide MONGO_USERNAME in the Render Dashboard

      - key: MONGO_PASSWORD
        sync: false # provide MONGO_PASSWORD in the Render Dashboard

      - key: MONGO_PORT
        value: 27017

      - key: MONGO_DB_NAME
        value: content

      - key: APP_PORT
        value: 3000

      - key: VERBOSE
        value: 1

      - key: DEBUG
        value: 1

      - key: TRACE
        value: 1

      - key: USE_MOCK_DB
        value: "true"
