apiVersion: v1
kind: Secret
metadata:
  name: content-crafters-secret
type: Opaque
data:
  mongo-uri: bW9uZ29kYitzcnY6Ly9wYWVzZ2kyMDI0OllRUkczY29hWG9KemNwNFFAY29udGVudC1jcmFmdGVycy1kYi54cG43NTBuLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1jb250ZW50LWNyYWZ0ZXJzLWRi
  mongo-username: cGFlc2dpMjAyNA==
  mongo-password: WVFSRzNjb2FYb0p6Y3A0UQ==
  mongo-port: MjcwMTc=
  mongo-db-name: Y29udGVudA==
